### ISSUE TITLE
Execute JavaScript Action in lores

### ISSUE THREAD

**Issue by Ismael-GT** [Arasple/TrMenuPro#10]
I need to execute javascript to get some results inside of the lores. It will be possible without use the "javascript Expansion"?
Something like this will be perfect: %TrUtils.runAction({player_name}, <js:X;>)%

**Comment by Arasple** [comment]
https://github.com/Arasple/TrMenuPro/blob/4ddcab9dbb06094f5c7259d4f540c2dee797137d/src/main/kotlin/me/arasple/mc/trmenupro/display/item/Item.kt#L92

This will be the TrMenuPro feature and it has been completed
