### ISSUE TITLE
建议在display、actions里的节点支持正规表达式...

### ISSUE THREAD

**Issue by 130B** [Arasple/TrMenuPro#4]
建议在display、actions里的节点支持正规表达式，例如 "\n、\r"等，
List<List<String>>里的 \n 可以直接当做下一行

有时候有些插件的PAPI变量会包含正规表达式的内容，希望能在TrMenu也能识别

**Comment by 130B** [comment]
额。。。这个建议之前不是被close了吗

**Comment by Arasple** [comment]
TrMenuPro 看情况，应该会写，还有什么意见也可以在这里的issue写

**Comment by Arasple** [comment]
已支持
