### ISSUE TITLE
Action Feature in "Click Type"

### ISSUE THREAD

**Issue by Ismael-GT** [Arasple/TrMenuPro#7]
I have an action with:

SHIFT_LEFT
SHIFT_RIGHT
DOUBLE_CLICK

And another group with:

DROP
CONTROL_DROP

- The feature is the possibility to add something like:
`      (shift_left,shift_right,double click):`

I have like 20/30 lines of commands in each Click Type, and my .yml is fully repeating the same line commands in each click type.

Grouping it will be more organized without repeat it.

**Comment by Arasple** [comment]
Done :)
